#ifndef MUTEX_ERRORS_H_
#define MUTEX_ERRORS_H_

#define MUTEX_ERROR_START					1000
#define MUTEX_ERROR_LOCK_WAIT_ABANDONED		(MUTEX_ERROR_START + 1)
#define MUTEX_ERROR_LOCK_ERROR				(MUTEX_ERROR_START + 2)
#define MUTEX_ERROR_CANT_RELEASE_MUTEX		(MUTEX_ERROR_START + 3)

#endif