#ifndef THREAD_ERRORS_H_
#define THREAD_ERRORS_H_

#define THREAD_ERROR_START					1000
#define THREAD_ERROR_FUNCTION_POINTER_NULL	(THREAD_ERROR_START + 1)
#define THREAD_ERROR_PARAM_POINTER_NULL		(THREAD_ERROR_START + 2)
#define THREAD_ERROR_NO_RUNNING_THREAD		(THREAD_ERROR_START + 3)
#define THREAD_ERROR_CANT_CLOSE_THREAD		(THREAD_ERROR_START + 4)
#define THREAD_ERROR_CANT_START_THREAD		(THREAD_ERROR_START + 5)
#endif